// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hyirvblqjcfukyithljg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh5aXJ2YmxxamNmdWt5aXRobGpnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ5MTczMDEsImV4cCI6MjA3MDQ5MzMwMX0.9BOgWlFE0vhcwAReE7FGt6tenirHtSgHprwyp7_o8XE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});